### ISSUE TITLE
I try to make it work

### ISSUE THREAD

**Issue by ogmkp** [jeffmikels/ptz-server#4]
Hello and thank you for this repo.

I don't know much about nodejs, I'm trying to set up a visca over IP camera but I get this error message:

```
ptz-server-main/dist/config.js:19
    viscaIPCameras: [192.168.0.110:52381],
                            ^^

SyntaxError: Unexpected number
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/maxime/Téléchargements/ptz-server-main/dist/app.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```
How to make it work?

**Comment by ogmkp** [comment]
This project seems to be dead, so I'm closing this issue.
